- name: Install python 3 and dependencies
  apt:
    update_cache: yes
    name: "{{ packages }}"
    force: yes
    state: present
  vars:
    packages:
    - python3
    - python3-pip
  become: yes
  tags:
   - python
   - python.install

- name: PIP dependencies
  become: yes
  pip:
    name:
      - openshift >= 0.6
      - PyYAML >= 3.11
  tags:
    - python
    - python.dependencies
