# VirtualBox
- name: apt-get update
  become: yes
  apt:
    update_cache: yes
  tags:
    - virtualbox
    - virtualbox.apt_update

- name: Install VirtualBox dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5x11extras5
      - libsdl1.2debian
      - libsdl-ttf2.0-0
      - libopus0
      - libcurl4
      - libvpx5
      - libxmu6
      - dkms
      - psmisc
      - apt-transport-https
  tags:
    - virtualbox
    - virtualbox.install_deps

- name: Create a directory if it does not exist
  become: yes
  file:
    path: /root/app
    state: directory
    mode: '0755'
  tags:
    - virtualbox
    - virtualbox.mkdir

- name: Ensure a locale exists
  become: yes
  locale_gen:
    name: en_US.UTF-8
    state: present
  tags:
    - virtualbox
    - virtualbox.locale

- name: Download VirtualBox
  become: yes
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.0.10/virtualbox-6.0_6.0.10-132072~Ubuntu~bionic_amd64.deb
    dest: /root/app/virtualbox-6.0_6.0.10-132072~Ubuntu~bionic_amd64.deb
    mode: 0440
  tags:
    - virtualbox
    - virtualbox.download_virtualbox

- name: Install VirtualBox
  become: yes
  command: "dpkg -i /root/app/virtualbox-6.0_6.0.10-132072~Ubuntu~bionic_amd64.deb"
  args:
    chdir: /root/app
  register: install_virtualbox
  changed_when: False
  tags:
    - virtualbox
    - virtualbox.install_virtualbox
