- name: Create a directory if it does not exist
  become: yes
  file:
    path: /root/app
    state: directory
    mode: '0700'
  tags:
    - minikube
    - minikube.mkdir

- name: Download Minikube
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /root/app/minikube-linux-amd64
    mode: 0644
  tags:
    - minikube
    - minikube.download

- name: Copy Minikube
  become: yes
  copy:
    src: /root/app/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    remote_src: true
    mode: '0777'
  tags:
    - minikube
    - minikube.copy

- name: Start minikube
  become: yes
  command: minikube start --vm-driver=none  --extra-config=apiserver.service-node-port-range=80-30000
  changed_when: False
  tags:
    - minikube
    - minikube.start
