- name: Create a directory if it does not exist
  become: yes
  file:
    path: /root/app
    state: directory
    mode: '0700'

- name: Download Minikube
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /root/app/minikube-linux-amd64
    mode: 0440

- name: Install Minikube
  become: yes
  copy:
    src: /root/app/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    remote_src: true
    mode: '0644'

#
- name: Start minikube
  command: minikube start --vm-driver=none
  become: yes
  changed_when: False

#- name: Debug kubectl_cluster_info
#  become: yes
#  debug:
#    var: kubectl_cluster_info
#
#- name: Stop minikube
#  become: yes
#  shell: "minikube stop"
#  register: stop_minikube
#
#- name: Debug stop_minikube
#  become: yes
#  debug:
#    var: stop_minikube
#
#- name: Delete minikube
#  shell: "minikube delete"
#  become: yes
#  register: delete_minikube
#
#- name: Debug delete_minikube
#  become: yes
#  debug:
#    var: delete_minikube
